version: '3'
services:
  buf:
    # For Debug
    build:
      context: .
    # image: ghcr.io/tk42/bufbuild
    volumes:
      - ".:/workspace"
    working_dir: "/workspace"
    command: ["generate", "petapis"]
